### ISSUE TITLE
child.stderr to output

### ISSUE THREAD

**Issue by mhitza** [francisdaigle/node-wkhtmltopdf#2]
In order to debug issues I've had when executing the pdf generation I found it really useful to set `child.stderr.pipe(process.stdout);`. I'd push that change as well but idk if you'd like it to be enabled by an additional flag, or have options include an additional parameter just for this.

**Comment by francisdaigle** [comment]
Hmmm... I see what you're saying.

In the spirit of keeping things simple, might it be better to return the child process itself:

```
return child;
```

rather than the current:

```
return child.stdout;
```

That way there's no need for an option/flag and you're free to do what you want with the returned process (eg. "child.stderr").

What do you think?

**Comment by mhitza** [comment]
That would work well for me. I didn't think of suggesting a backwards incompatible change just to simplify debugging.

**Comment by francisdaigle** [comment]
Yeah. I'll just tag it as "v2.0.0".

**Comment by francisdaigle** [comment]
Module has been changed so as to return "child_process" sans "stdout". Server implementation has been added. Testing has been improved. 

Thanks @mhitza - I thanked you for your suggestion in the "change log". Please let me know if you have any further suggestions.

Cheers :)
